jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/vasya-dancehall/image-to-latex.git
      path: /outputs/repo
    

  AddData:
    resources:
      instance-type: C4
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
      data: 
        type: dataset
        with:
          ref: im2latex:8obuumx
    outputs:
      repo:
        type: volume
    uses: script@v1
    with:
      script: |-
        cp -R /inputs/repo /outputs
        cd /outputs/repo
        mkdir /outputs/repo/data
        ln -s /inputs/data/data /outputs/repo/data
      image: python



  InstallPrereq:
    resources:
      instance-type: C4
    needs:
      - AddData
    inputs:
      repo: AddData.outputs.repo
    outputs:
      data:
        type: dataset
        with:
          ref: repo

    uses: script@v1
    with:
      script: |-
        cp -R /inputs/repo /image2latex      
        cd /image2latex
        python3 -m venv venv
        source venv/bin/activate
        apt-get update
        apt -y install build-essential
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e ".[dev]" --no-cache-dir
        cp -R /image2latex /outputs/data
      image: nvcr.io/nvidia/pytorch:21.10-py3



