jobs:
  AddData:
    resources:
      instance-type: C4
    inputs:
      repo:
        type: dataset
        with:
          ref: repo:cn9ewai
      data:
        type: dataset
        with:
          ref: im2latex:8obuumx
    outputs:
      repo:
        type: dataset
        with:
          ref: repo
    uses: script@v1
    with:
      script: |-
        apt-get update
        apt-get -y install rsync tree 
        tree -d -L 4 /inputs
        rsync -r  /inputs/repo/ /outputs
        cd /outputs
        tree -d -L 4
        mkdir /outputs/image2latex/data
        ls
        ln -s /inputs/data/data /outputs/image2latex/data
      image: ubuntu:latest
