jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/vasya-dancehall/image-to-latex.git
      path: /outputs/repo

  InstallPrereq:
    resources:
      instance-type: C4
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      data:
        type: dataset
        with:
          ref: im2latex


    uses: script@v1
    with:
      script: |-
        cp -R inputs/repo /image2latex      
        cd /image2latex
        python3 -m venv venv
        source venv/bin/activate
        apt-get update
        apt -y install build-essential
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e ".[dev]" --no-cache-dir
        pip install pre-commit
        pre-commit install
        pre-commit autoupdate
        pip uninstall dataclasses -y
        pip install googledrivedownloader
        ls
        python3 scripts/get_data.py
      image: shevonkuan/image-to-latex:latest



