jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/vasya-dancehall/image-to-latex.git
  Prepare:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
        script: |-
          cp -R inputs/repo /image-to-latex
          python -m pip install -e . --no-cache-dir
        image: paperspace/gradient-base:tf24-py36-0.10
          