jobs:
  CloneRepo:
    resources:
      instance-type: C5
    uses: git-checkout@v1
    with:
      url: https://github.com/vasya-dancehall/image-to-latex.git
    uses: script@v1
    with:
      script: |-
        python3 -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -e .
      image: brunneis/python:3.8.3-ubuntu-20.04
    
          
