# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
  
      - name: install dev req
        run: |
          apt-get update \
          && apt-get install -y --no-install-recommends gcc build-essential \
          && rm -rf /var/lib/apt/lists/* \
          && python -m pip install --upgrade pip setuptools wheel \
          && python -m pip install -e . --no-cache-dir \
          && apt-get purge -y --auto-remove gcc build-essential
